export const dummyPlaylist = [
    {
        "id": 1,
        "playlistName": "Bollywood Love Anthems",
        "playlistDescription": "Romantic Bollywood songs perfect for date nights and special moments.",
        "songsInthePlaylist": [
            {"id": 1, "songName": "Tum Hi Ho", "songDesc": "A soulful love song from Aashiqui 2.", "imageSrc": "songImage1.webp"},
            {"id": 2, "songName": "Tera Ban Jaunga", "songDesc": "A romantic track from Kabir Singh.", "imageSrc": "songImage2.jpeg"},
            {"id": 3, "songName": "Raabta", "songDesc": "A timeless love song from Agent Vinod.", "imageSrc": "songImage3.png"},
            {"id": 4, "songName": "Ae Dil Hai Mushkil", "songDesc": "An intense love anthem from the movie with the same name.", "imageSrc": "songImage4.jpg"},
            {"id": 5, "songName": "Jeene Laga Hoon", "songDesc": "A feel-good romantic song from Ramaiya Vastavaiya.", "imageSrc": "songImage5.jpg"},
            {"id": 6, "songName": "Mast Magan", "songDesc": "Soulful melody from 2 States.", "imageSrc": "songImage1.webp"},
            {"id": 7, "songName": "Sun Saathiya", "songDesc": "A passionate song from ABCD 2.", "imageSrc": "songImage2.jpeg"},
            {"id": 8, "songName": "Kaun Tujhe", "songDesc": "A beautiful track from MS Dhoni.", "imageSrc": "songImage3.png"},
            {"id": 9, "songName": "Janam Janam", "songDesc": "A song about eternal love from Dilwale.", "imageSrc": "songImage4.jpg"},
            {"id": 10, "songName": "Pehla Nasha", "songDesc": "A classic love song from Jo Jeeta Wohi Sikandar.", "imageSrc": "songImage5.jpg"},
            {"id": 11, "songName": "Hasi Ban Gaye", "songDesc": "A touching love song from Hamari Adhuri Kahani.", "imageSrc": "songImage1.webp"},
            {"id": 12, "songName": "Dil Diyan Gallan", "songDesc": "A sweet romantic track from Tiger Zinda Hai.", "imageSrc": "songImage2.jpeg"},
            {"id": 13, "songName": "Tum Jo Aaye", "songDesc": "A heartfelt song from Once Upon a Time in Mumbaai.", "imageSrc": "songImage3.png"},
            {"id": 14, "songName": "Tera Hone Laga Hoon", "songDesc": "A romantic track from Ajab Prem Ki Ghazab Kahani.", "imageSrc": "songImage4.jpg"},
            {"id": 15, "songName": "Tujh Mein Rab Dikhta Hai", "songDesc": "A song about finding love in God from Rab Ne Bana Di Jodi.", "imageSrc": "songImage5.jpg"},
            {"id": 16, "songName": "Sajde", "songDesc": "A soothing romantic song from Kill Dil.", "imageSrc": "songImage1.webp"},
            {"id": 17, "songName": "Khuda Jaane", "songDesc": "A passionate love song from Bachna Ae Haseeno.", "imageSrc": "songImage2.jpeg"},
            {"id": 18, "songName": "Raaz Aankhein Teri", "songDesc": "A soft love ballad from Raaz Reboot.", "imageSrc": "songImage3.png"},
            {"id": 19, "songName": "Galliyan", "songDesc": "A heartfelt song from Ek Villain.", "imageSrc": "songImage4.jpg"},
            {"id": 20, "songName": "Janam Janam", "songDesc": "Another beautiful track from Dilwale.", "imageSrc": "songImage5.jpg"}
        ]
    },
    {
        "id": 2,
        "playlistName": "Punjabi Party Hits",
        "playlistDescription": "Energetic Punjabi songs for any celebration or gathering.",
        "songsInthePlaylist": [
            {"id": 1, "songName": "Lahore", "songDesc": "A popular party track by Guru Randhawa.", "imageSrc": "songImage1.webp"},
            {"id": 2, "songName": "3 Peg", "songDesc": "A fun song by Sharry Mann.", "imageSrc": "songImage2.jpeg"},
            {"id": 3, "songName": "High Rated Gabru", "songDesc": "An energetic track by Guru Randhawa.", "imageSrc": "songImage3.png"},
            {"id": 4, "songName": "Patola", "songDesc": "A catchy track by Guru Randhawa.", "imageSrc": "songImage4.jpg"},
            {"id": 5, "songName": "Suit Suit", "songDesc": "A peppy song also featured in Hindi Medium.", "imageSrc": "songImage5.jpg"},
            {"id": 6, "songName": "Bapu Zimidar", "songDesc": "A popular track by Jassi Gill.", "imageSrc": "songImage1.webp"},
            {"id": 7, "songName": "Makhna", "songDesc": "A Yo Yo Honey Singh hit.", "imageSrc": "songImage2.jpeg"},
            {"id": 8, "songName": "Lehanga", "songDesc": "A chart-topper by Jass Manak.", "imageSrc": "songImage3.png"},
            {"id": 9, "songName": "Naah", "songDesc": "A fun track by Harrdy Sandhu.", "imageSrc": "songImage4.jpg"},
            {"id": 10, "songName": "Brown Munde", "songDesc": "A Punjabi anthem by AP Dhillon.", "imageSrc": "songImage5.jpg"},
            {"id": 11, "songName": "Yaar Mod Do", "songDesc": "An emotional song by Guru Randhawa.", "imageSrc": "songImage1.webp"},
            {"id": 12, "songName": "Ishare Tere", "songDesc": "A fun duet by Guru Randhawa and Dhvani Bhanushali.", "imageSrc": "songImage2.jpeg"},
            {"id": 13, "songName": "Do You Know", "songDesc": "A popular track by Diljit Dosanjh.", "imageSrc": "songImage3.png"},
            {"id": 14, "songName": "Raat Di Gedi", "songDesc": "A fun song by Diljit Dosanjh.", "imageSrc": "songImage4.jpg"},
            {"id": 15, "songName": "Backbone", "songDesc": "A soulful track by Harrdy Sandhu.", "imageSrc": "songImage5.jpg"},
            {"id": 16, "songName": "Wakhra Swag", "songDesc": "A stylish track by Navv Inder and Badshah.", "imageSrc": "songImage1.webp"},
            {"id": 17, "songName": "Nikle Currant", "songDesc": "A peppy duet by Neha Kakkar and Jassie Gill.", "imageSrc": "songImage2.jpeg"},
            {"id": 18, "songName": "Nira Ishq", "songDesc": "A hit love song by Guri.", "imageSrc": "songImage3.png"},
            {"id": 19, "songName": "Photo", "songDesc": "A romantic track by Karan Sehmbi.", "imageSrc": "songImage4.jpg"},
            {"id": 20, "songName": "Taare", "songDesc": "A touching track by Aatish.", "imageSrc": "songImage5.jpg"}
        ]
    },
    {
        "id": 3,
        "playlistName": "Workout Boost",
        "playlistDescription": "Get pumped with these high-energy Hindi and Punjabi tracks.",
        "songsInthePlaylist": [
            {"id": 1, "songName": "Apna Time Aayega", "songDesc": "Motivational rap from Gully Boy.", "imageSrc": "songImage1.webp"},
            {"id": 2, "songName": "Zinda", "songDesc": "An inspiring track from Bhaag Milkha Bhaag.", "imageSrc": "songImage2.jpeg"},
            {"id": 3, "songName": "Malang", "songDesc": "An upbeat song from the movie Malang.", "imageSrc": "songImage3.png"},
            {"id": 4, "songName": "Baazigar", "songDesc": "Energetic track by Divine.", "imageSrc": "songImage4.jpg"},
            {"id": 5, "songName": "Sher Aaya Sher", "songDesc": "Powerful song from Gully Boy.", "imageSrc": "songImage5.jpg"},
            {"id": 6, "songName": "Bum Bum Bhole", "songDesc": "An intense song from Taare Zameen Par.", "imageSrc": "songImage1.webp"},
            {"id": 7, "songName": "Lungi Dance", "songDesc": "Party track from Chennai Express.", "imageSrc": "songImage2.jpeg"},
            {"id": 8, "songName": "All Black", "songDesc": "A Punjabi track by Sukhe.", "imageSrc": "songImage3.png"},
            {"id": 9, "songName": "Wakhra Swag", "songDesc": "Catchy tune by Navv Inder.", "imageSrc": "songImage4.jpg"},
            {"id": 10, "songName": "Proper Patola", "songDesc": "A track by Diljit Dosanjh.", "imageSrc": "songImage5.jpg"},
            {"id": 11, "songName": "Chogada", "songDesc": "Garba beat from Loveyatri.", "imageSrc": "songImage1.webp"},
            {"id": 12, "songName": "Dhakad", "songDesc": "Song from Dangal.", "imageSrc": "songImage2.jpeg"},
            {"id": 13, "songName": "Gabru", "songDesc": "Track by J Star.", "imageSrc": "songImage3.png"},
            {"id": 14, "songName": "Bom Diggy Diggy", "songDesc": "Party anthem from Sonu Ke Titu Ki Sweety.", "imageSrc": "songImage4.jpg"},
            {"id": 15, "songName": "Kar Gayi Chull", "songDesc": "Energetic track from Kapoor & Sons.", "imageSrc": "songImage5.jpg"},
            {"id": 16, "songName": "Nakhre", "songDesc": "Dance track by Jassi Gill.", "imageSrc": "songImage1.webp"},
            {"id": 17, "songName": "Kala Chashma", "songDesc": "A peppy song from Baar Baar Dekho.", "imageSrc": "songImage2.jpeg"},
            {"id": 18, "songName": "Saturday Saturday", "songDesc": "A hit party song from Humpty Sharma Ki Dulhania.", "imageSrc": "songImage3.png"},
            {"id": 19, "songName": "High Heels Te Nachche", "songDesc": "Upbeat song by Honey Singh.", "imageSrc": "songImage4.jpg"},
            {"id": 20, "songName": "Party All Night", "songDesc": "A lively song by Honey Singh.", "imageSrc": "songImage5.jpg"}
        ]
    },
    {
        "id": 4,
        "playlistName": "Bollywood Sad Songs",
        "playlistDescription": "Melancholic Bollywood tunes for a reflective mood.",
        "songsInthePlaylist": [
            {"id": 1, "songName": "Bekhayali", "songDesc": "Emotional track from Kabir Singh.", "imageSrc": "songImage1.webp"},
            {"id": 2, "songName": "Channa Mereya", "songDesc": "Heartfelt song from Ae Dil Hai Mushkil.", "imageSrc": "songImage2.jpeg"},
            {"id": 3, "songName": "Jeene Bhi De", "songDesc": "Touching song by Badshah.", "imageSrc": "songImage3.png"},
            {"id": 4, "songName": "Pachtaoge", "songDesc": "A soulful Arijit Singh song.", "imageSrc": "songImage4.jpg"},
            {"id": 5, "songName": "Agar Tum Saath Ho", "songDesc": "Emotional song from Tamasha.", "imageSrc": "songImage5.jpg"},
            {"id": 6, "songName": "Kabira", "songDesc": "A sentimental track from Yeh Jawaani Hai Deewani.", "imageSrc": "songImage1.webp"},
            {"id": 7, "songName": "Bhula Dena", "songDesc": "Heart-wrenching song from Aashiqui 2.", "imageSrc": "songImage2.jpeg"},
            {"id": 8, "songName": "Phir Bhi Tumko Chaahunga", "songDesc": "Sad song from Half Girlfriend.", "imageSrc": "songImage3.png"},
            {"id": 9, "songName": "Hasi", "songDesc": "A song from Hamari Adhuri Kahani.", "imageSrc": "songImage4.jpg"},
            {"id": 10, "songName": "Humdard", "songDesc": "A soulful song from Ek Villain.", "imageSrc": "songImage5.jpg"},
            {"id": 11, "songName": "Tera Yaar Hoon Main", "songDesc": "A nostalgic friendship track from Sonu Ke Titu Ki Sweety.", "imageSrc": "songImage1.webp"},
            {"id": 12, "songName": "Mile Ho Tum Humko", "songDesc": "Romantic song by Neha Kakkar.", "imageSrc": "songImage2.jpeg"},
            {"id": 13, "songName": "Tera Hone Laga Hoon", "songDesc": "Romantic track from Ajab Prem Ki Ghazab Kahani.", "imageSrc": "songImage3.png"},
            {"id": 14, "songName": "Tum Mile", "songDesc": "Romantic song from Tum Mile.", "imageSrc": "songImage4.jpg"},
            {"id": 15, "songName": "Tujh Mein Rab Dikhta Hai", "songDesc": "Song from Rab Ne Bana Di Jodi.", "imageSrc": "songImage5.jpg"},
            {"id": 16, "songName": "Hasi Ban Gaye", "songDesc": "A touching song from Hamari Adhuri Kahani.", "imageSrc": "songImage1.webp"},
            {"id": 17, "songName": "Soch Na Sake", "songDesc": "Emotional song from Airlift.", "imageSrc": "songImage2.jpeg"},
            {"id": 18, "songName": "Sun Saathiya", "songDesc": "Dance song from ABCD 2.", "imageSrc": "songImage3.png"},
            {"id": 19, "songName": "Kabhi Jo Baadal Barse", "songDesc": "Song by Arijit Singh.", "imageSrc": "songImage4.jpg"},
            {"id": 20, "songName": "Aayat", "songDesc": "A heart-wrenching song from Bajirao Mastani.", "imageSrc": "songImage5.jpg"}
        ]
    },
    {
        "id": 5,
        "playlistName": "Chill Vibes",
        "playlistDescription": "Relaxing tracks to enjoy your downtime.",
        "songsInthePlaylist": [
            {"id": 1, "songName": "Jeene Laga Hoon", "songDesc": "Soothing song from Ramaiya Vastavaiya.", "imageSrc": "songImage1.webp"},
            {"id": 2, "songName": "Dil Dhadakne Do", "songDesc": "Easy-going track from ZNMD.", "imageSrc": "songImage2.jpeg"},
            {"id": 3, "songName": "Ilahi", "songDesc": "A soulful track from Yeh Jawaani Hai Deewani.", "imageSrc": "songImage3.png"},
            {"id": 4, "songName": "Safarnama", "songDesc": "A song about travel from Tamasha.", "imageSrc": "songImage4.jpg"},
            {"id": 5, "songName": "Tera Ban Jaunga", "songDesc": "A love song from Kabir Singh.", "imageSrc": "songImage5.jpg"},
            {"id": 6, "songName": "Tera Hone Laga Hoon", "songDesc": "A romantic tune from Ajab Prem Ki Ghazab Kahani.", "imageSrc": "songImage1.webp"},
            {"id": 7, "songName": "Khairiyat", "songDesc": "A slow track from Chhichhore.", "imageSrc": "songImage2.jpeg"},
            {"id": 8, "songName": "Dil Chahta Hai", "songDesc": "Title track from Dil Chahta Hai.", "imageSrc": "songImage3.png"},
            {"id": 9, "songName": "Zindagi Do Pal Ki", "songDesc": "Relaxing track from Kites.", "imageSrc": "songImage4.jpg"},
            {"id": 10, "songName": "Raabta", "songDesc": "Soulful song from Agent Vinod.", "imageSrc": "songImage5.jpg"},
            {"id": 11, "songName": "Tum Mile", "songDesc": "Soft song from Tum Mile.", "imageSrc": "songImage1.webp"},
            {"id": 12, "songName": "Phir Se Udd Chala", "songDesc": "A calming track from Rockstar.", "imageSrc": "songImage2.jpeg"},
            {"id": 13, "songName": "Kya Mujhe Pyaar Hai", "songDesc": "Romantic song from Woh Lamhe.", "imageSrc": "songImage3.png"},
            {"id": 14, "songName": "Kun Faya Kun", "songDesc": "Soulful track from Rockstar.", "imageSrc": "songImage4.jpg"},
            {"id": 15, "songName": "Pee Loon", "songDesc": "A song from Once Upon a Time in Mumbaai.", "imageSrc": "songImage5.jpg"},
            {"id": 16, "songName": "Peeche Peeche", "songDesc": "A light track by Armaan Malik.", "imageSrc": "songImage1.webp"},
            {"id": 17, "songName": "Hasi", "songDesc": "A soft tune from Hamari Adhuri Kahani.", "imageSrc": "songImage2.jpeg"},
            {"id": 18, "songName": "Kyon", "songDesc": "A soft song from Barfi!", "imageSrc": "songImage3.png"},
            {"id": 19, "songName": "Tum Se Hi", "songDesc": "A romantic track from Jab We Met.", "imageSrc": "songImage4.jpg"},
            {"id": 20, "songName": "Phir Le Aaya Dil", "songDesc": "A song from Barfi!", "imageSrc": "songImage5.jpg"}
        ]
    }
]
